### ISSUE TITLE
Export route as GPX (without starting a collaborative map)

### ISSUE THREAD

**Issue by narcisgarcia** [FacilMap/facilmap2#31]
As of November 23th, facilmap.org's option "Export GPX" offers a file with 2 (random) points only.
My test case:
1. Open facilmap.org with M.Firefox 49
2. Find Paris (administrative) and select as start point
3. Find Rome (administrative) as next step
4. Click on "Go!"
5. Click "Start collaborative map", press "Create".
6. Open "Tools" and select "Export GPX"
7. Save the offered file "New FacilMap.gpx"
The result is a file with only 692 bytes with no tracks.

**Comment by cdauth** [comment]
Thanks for your report, that is indeed a bit confusing.

The “Export GPX” function only exports any markers and lines that are saved to the collaborative map. When you search for something or calculate a route, that is only shown on your screen, it is not yet part of the collaborative map. Only after you add it to the map (for routes, click the “Add to map” button in the routing form), it will be part of the collaborative map and thus the exported GPX.

I don’t see two random points added to the GPX file when following your steps. There are only the two default object types "Marker" and "Line" added to it. (Those are there because the GPX function was originally thought to export whole collaborative maps, with all views, object types, etc., but I will change that soon.)

Maybe I will add a button “Export GPX” to the routing form, to export just the current route, without having to start a collaborative map?

**Comment by narcisgarcia** [comment]
With this steps GPX file results empty too:
1. Click "Start collaborative map", press "Create".
2. Find Paris (administrative) and select as start point
3. Find Rome (administrative) as next step
4. Click on "Go!"
5. Open "Tools" and select "Export GPX"

As loadable are GPX files, I believe that anything drawable should be exportable to GPX, in any working mode.

**Comment by cdauth** [comment]
Between step 4 and 5 you have to click on “Add to map” in the routing form.

**Comment by narcisgarcia** [comment]
With this last step correction, it works for me. I believe it's very unclear for most people who wants to simply draw a route and save/send it.

**Comment by narcisgarcia** [comment]
The main problem I see about this, is that visitor doesn't see the separation between client editor data and server data. "Export to GPX" suggests that you can import/edit/export all at client side without server storage, just as GPSies does.
